# Define a service for forwarding ports to the app
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      name: nginx
      targetPort: 80
      nodePort: 32756
  selector:
    app: nginx

---

# Create a Deployment that creates a replica set of 3 nginx containers
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginxdeployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginxcontainer
          image: nginx: latest
          imagePullPolicy: always
          ports:
            - containerPort: 80
