[package]
name = "saveprincess"
version = "0.1.0"
authors = ["John Ellis <john.ellis1392@gmail.com>"]

[lib]
name = "lib"
path = "src/lib.rs"


[[bin]]
name = "main"
path = "src/main.rs"


[dependencies]
